# ai/reporting/report_generator.py
from pathlib import Path

def generate_report(state, out_dir):
    """
    Generates a high-level Markdown report summarizing the software factory execution.
    """
    report_path = Path(out_dir) / "GENERATION_REPORT.md"
    
    content = f"""# 📊 Software Generation Report: {state.project_name.upper()}

## 💡 Business Concept
{state.idea}

## 🏗️ Technical Summary
- **Architecture Style:** Hexagonal / Clean Architecture
- **Design Pattern:** Domain-Driven Design (DDD)
- **Execution Status:** {state.status}
- **Artifacts Generated:** {len(state.generated_files)} files

## 📂 Delivered File Inventory
"""
    for file in state.generated_files:
        content += f"- ✅ `{file}`\n"

    content += f"""
## 🛡️ Quality Assurance & Compliance
Every generated file has undergone a rigorous auditing process by the **Principal Architectural Auditor Agent**, ensuring strict adherence to Java 17 standards, Lombok best practices, and Hexagonal layer isolation.

---
*Professional software generated by the Industrial Domain-Driven AI Factory.*
"""
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(content)